base_dir:   depmap-22Q2
source_dir: input          # relative to base_dir

thread: 12

################## SNAKEFILE PARAMETERS #####################

output_dir: output-v18-with-AF-without-filter        # relative to base_dir
version:    v18-af             # v7 or v7-af


#################### RULES PARAMETERS #######################

depmap:
  filter_af: "$30 != \"\"" # (column 30: RNAseq_AC)
  isCOSMIChotspot: False

complexity:
  enabled:   True  # if True, complexity is applied

filter:
  enabled:   False  # if True, filter is applied
  recur-max: 100%  # absolute or percentage (ex: 100 or 70%)
  abund-min: 6     # noise level

merge_kmer:
  min_pos: 3       # Minimum number of positive counts (default: 1)

################# OTHER SNAKEFILE PARAMETERS ####################

kmerator:
  release: 108    # transcriptome release
  jellyfish:  /data/indexes/jellyfish/human/GRCh37_canonical.jf

genome:     genomes/GRCh37.primary_assembly.genome.fa

annot:
  version: GRCh37
  release: 42

reindeer:
  index:  "CCLE-1019-cut-disk"
  server: "janis"
  options: "-t 0"

########################## SAMPLES ############################

genes:
  - APC
  - ARID1A
  - ATM
  - ATRX
  - BAP1
  - BRCA2
  - CDH1
  - CDKN2A       # src: Publi
  - CTCF
  - CTNNB1
  - DNMT3A       # src: Myeloid
  - EGFR         # src: Publi
  - FBXW7
  - FLT3         # src: Myeloid
  - GATA3
  - IDH1         # src: Myeloid
  - KRAS         # src: Publi
  - MAP3K1
  #~ - MLL2
  #~ - MLL3
  - MTOR
  - NAV3
  - NCOR1
  - NF1
  - NOTCH1
  - NPM1         # src: Myeloid
  - PBRM1
  - PIK3CA       # src: Publi
  - PIK3R1       # src: All
  - PTEN
  - RB1
  - RUNX1        # src: Myeloid
  - SETD2
  - STAG2
  - TAF1
  - TP53         # src: Publi
  - VHL
  - ASXL1        # src: Myeloid
  - BRAF         # src: Publi
  - CEBPA        # src: Myeloid
  - CFB          # src: Myeloid
  - CREBBP       # src: Myeloid
  - EZH2         # src: Myeloid
  - IDH2         # src: Myeloid
  - NRAS         # src: Publi
  - RUNX2        # src: Myeloid
  - SRSF2        # src: Myeloid
  - TCF24        # src: All
  - TET2         # src: Myeloid
  - ZNF444       # src: All
  - CBL
  - UBA1
  # - HOXA5      # src: Myeloid
  # - HOXA10     # src: Myeloid
  # - HOXB-AS3   # src: Myeloid
  # - HOXB5      # src: Myeloid
  # - HOXB9      # src: Myeloid
  # - POU3F1     # src: All
